version: "1.0"
stages:
  - "clone"
  - "build"
  - "test"
  - "push"
steps:
  main_clone:
    type: "git-clone"
    description: "Cloning main repository..."
    repo: "octarinesec/validator"
    revision: "${{CF_BRANCH}}"
    stage: "clone"
  ValidatorImage:
    title: "Building Docker Image"
    type: "build"
    image_name: "octarinesec/validator"
    tag: "${{CF_REVISION}}"
    dockerfile: "Dockerfile"
    stage: "build"
  UnitTests:
    title: "Running Unit Tests"
    type: "freestyle"
    image: ${{ValidatorImage}}
    commands:
      - pipenv run pytest
    stage: "test"
  push_master:
    title: "Pushing image to Dockerhub"
    type: "push"
    image_name: "octarinesec/validator"
    registry: "dockerhub"
    candidate: "${{ValidatorImage}}"
    when:
      branch:
        only:
          - master
    tags:
      - "${{CF_REVISION}}"
    stage: "push"
  push_release:
    title: "Pushing image to Dockerhub"
    type: "push"
    image_name: "octarinesec/validator"
    registry: "dockerhub"
    candidate: "${{ValidatorImage}}"
    when:
      condition:
        all:
          triggerByRelease: 'includes("${{CF_RELEASE_TAG}}", "{{CF_RELEASE_TAG}}") == false'

    tags:
      - "${{CF_RELEASE_TAG}}"
    stage: "push"
